elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://localhost:9200'
    restart: always
    ports:
    - "127.0.0.1:9114:9114"